### ISSUE TITLE
What is series nature?

### ISSUE THREAD

**Issue by andrew2net** [riboseinc/iso690xml#4]
@ronaldtse I don't understand what is nature of `bibitem/series`. Could you explain?

**Comment by ronaldtse** [comment]
I think @opoudjis could explain better than myself, but it is basically for representing a "series" like a journal series, a document series.

**Comment by opoudjis** [comment]
That is correct. I will paste in the text from the draft proposal about it.

**Comment by opoudjis** [comment]
A series is the name of a collection under which the item has been published. The collection is published by the same organisation, over a period of time and with multiple components. If the item is a journal article, the series is the journal (and is essential as the container of the article). If the item is a book, the series is the monograph series (which is somewhat less critical). 

If the item is a single standard, the series is the collection of standards badged in the same way. So RFC 0001 is the item, and RFC Standards are the series (IETF is the publisher of RFCs, and of Internet Drafts: they are two different series of standards). ISO Guide 37 is the item, and ISO Guides are the series; ISO Standards are a different series, published by the same publisher, ISO.

The *name* of the standard indicates the series it belongs to: *RFC* 0001, ISO *Guide* 37. (It is implicit in ISO Standards: ISO *[Standard]* 9001. Because we are breaking the item down into its components, we identify the series as a parent item for the item. We could model this as a document relation, between the item and the collection as a partOf relation. But for journal articles, the name of the journal is privileged as part of the reference so strongly, that it is consistently modelled as a top-level attribute, not just a relation between two kinds of document granularity.

If an item belongs to a series, the series has a name, and the item usually has an ordinal number within the series: RFC *0001*, Dr Dobbs Journal _56_. 

The model is richer than that for the possible components of series: series can have disambiguating places of publication and publishers; series can have standard abbreviations alongside their title (and of course "RFC" is an abbreviation of "Requests for Comments"); series can have a starting and ending number; and series can have a part-number (which is the volume vs issue division of a journal). In the case of RFC bibliographies, I don't think you need to bother with these, with the possible exception of leaving RFC  as the series abbreviation, and spelling out "Request of Comments" as the series title.

````
series = element series {
  attribute type { "main" | "alt" }?,
  ( btitle | formattedref ),
  bplace, seriesorganization,
  abbreviation?,
  seriesfrom?, seriesto?,
  seriesnumber?, seriespartnumber?
}
````
